// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_confirmareliminacion.cpp"
#include "EWIEGA46WW/moc_infoarma.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "EWIEGA46WW/moc_ventagregar.cpp"
